version: "3.7"

services:
  app:
    image: openjdk:8-jdk-alpine
    ports:
      - 8080:8080
      - 80:80
      - 443:443
    working_dir: /app
    volumes:
      - ./:/app
    entrypoint: ./run.sh

  mysql_db:
    image: mysql:8.0
    ports:
      - 8001:3306
    volumes:
      - hc_db:/data
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: health_calculator

volumes:
  hc_db: